### PR TITLE
Added option for selecting which path to use

### PR DESCRIPTION
**Pull request by scottrini**
Only two options right now - github or uploads.
Also added documentation for using SSH key authentication.

### CODE REVIEW

**Comment by OutsourcedGuru** [comment]
In the original set of commits, I initially put the folder under `~/.octoprint/uploads`. This resulted (as I recall) in a set of error messages by OctoPrint in its log. Next, I moved the folder to something like `~/gitfiles` perhaps. I barely recall the plot complication but for whatever reason (OctoPrint won't walk a symlink unfortunately), I put it back to live under uploads.

The reason why I didn't want the git folder to coincide with uploads is that that if the user uploads anything there, this will then create the need to support git merge behavior, making it unnecessarily complicated versus the dedicated folder.

Imagine this workflow:

* empty uploads folder
* add the plugin
* create the repository and do the git pull behind-the-scenes
* upload a file using the Files manager (especially one that already exists by name)
* attempt to do another git pull by pushing the button

At this point, the git command line just goes to the log and things are pretty messed up without any easy way to fix it unless you intimately know git commands (which you and I probably do).

------

Can you attach a screenshot of the Settings dialog box so that I can take a look before installing?

**Comment by scottrini** [comment]
Totally understand your concerns and I thought about that too, but I've just decided to always use git to sync my octoprint instances.  After octoprint sanitized my paths from my initial commit, I pushed from my octoprint instance to have the sanitized paths in my repo, so I wouldn't have to worry about it.

It might even be nice to have a button to push changes FROM octoprint in the case where someone would want to upload directly to it, but still, merge conflict issues can obviously be a problem. 

But these concerns are why I didn't want to force putting it in uploads and I wanted to add an option to allow the user to choose.  Maybe some more documentation in the README.md would help explain the concerns about having it take over all of uploads.

Additionally, I was thinking how we could easily remove the need for the initialized variable.  We could simply do a `git remote get-url origin` in the configured path.  Non-zero exit status obviously means it's not initialized.  Otherwise, we can capture the output of the command and compare it to the configure remote.  If it's a different remote, we need to re-initialize and set the proper remote.  Maybe that's over complicating things, but currently, I don't think it would handle changing repositories gracefully...

Here's a screenshot of how I have it setup on my instances currently.  c3po is my local NAS running GitLab.
https://i.imgur.com/jWqX9R1.png

**Comment by scottrini** [comment]
Also!  I forgot to mention that I definitely think the path option should be expanded.  I just created a dropdown with those two options to fill my need quickly and I wasn't sure if you'd be willing to pull it into the plugin or if I'd just be installing my own fork always.  I think ideally it would be a combobox (combination text input field, with dropdown for presets).  I think it should be structured where leaving it blank is the root uploads folder and anything you type in/select becomes a subdirectory of uploads.  I still think the option should default to 'github' or 'gitfiles' whatever, but there should be some note that explains if you clear it out (or select that preset from the drop-down), it can use the root uploads folder.

**Comment by OutsourcedGuru** [comment]
With proper education to the end-user, I don't see a problem with the approach that you've taken. I can't imagine an easy "button" which could push changes back, though, given the complexity.

If a subfolder is created under `uploads`, I don't think it technically needs to be `github` necessarily. In your case, you're using **gitlab** and you might have wanted that as a folder name, in theory.

I think the default should be to behave using the subfolder approach to make things easier for noobs. I probably need to think about the hover-over help text for some of this. I'll spend some time merging and testing this next week when the girlfriend has gone back to college, for sanity's sake. Feel free to add on here if you can think of anything else.

**Comment by scottrini** [comment]
Well, I agree a button that would push changes over complicates the plugin and should probably be left manual, if it's set to perform the same actions every time and just pull all changes, it is pretty simple.
`git pull origin master` (to ensure it's up to date)
`git add -A`
`git commit -am "Commit from Octoprint-Gitfiles on {date} by {host}"`
`git push origin master`

You can have issues with merge conflicts, but only if more than one source edits the same file.  I can see this working and might end up doing it in my own fork in a feature branch.

What you describe about the different subfolder name and defaulting to a subfolder I've covered in my earlier comments.  It currently defaults to the subfolder, as I think it should.  I was also saying I think it should be a text input so you could enter any subfolder name (I even prefer *gitfiles* since it matches the plugin name and is backend agnostic).  I might go ahead and update my PR for free input because I already liked that better.  Just like I mentioned, I wasn't sure if it would be considered and thought I might be using my own fork.

Take your time, I'm taking my family on vacation all next week too, but I might make a few updates and a feature branch first.  I'll probably take a stab and my suggestion for removing the initialized variable above in a feature branch.

**Comment by OutsourcedGuru** [comment]
I'm also sensitive to the workflow in which the user begins with folder named "a" and then changes their mind to "b". Do you attempt then to rename the existing folder in place or nuke the existing one and recreate? In each case where the user has pushed their own files manually then only the renaming one is safe enough. etc.

**Comment by scottrini** [comment]
I am too, which is why I was suggesting getting rid of the initialized variable.  Currently, switching folders won't work because initialized is persisted and wouldn't be reset.  So if you change the folder, it won't attempt to re-initialize the next time they try to pull files and won't work.  Currently, it also doesn't handle changing repositories, so that's another reason I was suggesting to remove the initialized variable.  We shouldn't be serializing the state of something we can check anyway, so it will be good to get rid of that.  

If the user pushed their own files or not won't have any affect on nuking vs renaming.  If we nuke, we'll just pull the changes they've pushed once we recreate it.   I'd even prefer giving the user the option to remove or rename.  There's a different route and disabling the path field in settings once files have been pulled, but I don't like that.

**Comment by n0dyjeff** [comment]
Would it be possible to merge the documentation on using the ssh URL, even if there is ongoing discussion about the path select? I was able to figure it out (and it works great!), but I'm sure there are others who would like to make use of that very convenient option.

**Comment by scottrini** [comment]
@n0dyjeff Sure, I'll cherry pick it into a separate branch and open a separate PR.  I'm glad you found it useful.  I exclusively use SSH with git.

**Comment by OutsourcedGuru** [comment]
Waiting for the girlfriend to head back out to her class. I'll then install your version and run it through its paces.

Out of curiosity, did you have to upload your public key to github so that you could use the `git` protocol? As a former software development instructor, my own students were usually blocked at any documentation which didn't use https://... instead.

**Comment by OutsourcedGuru** [comment]
Squash-merging, followed by testing, overall grooming/refactoring and a second set of eyeballs on everything you did. Expect a 1.1.4 label when completed today.

**Pull request merged**
